# Generated by Django 4.1.1 on 2022-09-20 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='telefone',
            new_name='telephone',
        ),
    ]
